# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class AnalysisResult:
    id: str
    session_id: str
    sentiment_score: float
    engagement_score: float
    lead_score: float
    intent_label: str
    summary: Optional[str]
    analysis_version: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class Booking:
    id: str
    session_id: str
    user_id: str
    scheduled_time: datetime.datetime
    timezone: Optional[str]
    status: str
    created_at: datetime.datetime


@dataclasses.dataclass()
class Session:
    id: str
    user_id: str
    started_at: datetime.datetime
    ended_at: Optional[datetime.datetime]
    duration_sec: Optional[int]
    booking_made: bool
    analysis_status: str
    analysis_version: int
    r2_report_path: Optional[str]
    r2_audio_path: Optional[str]
    analysis_attempts: int
    last_analysis_at: Optional[datetime.datetime]
    error_message: Optional[str]
    created_at: datetime.datetime


@dataclasses.dataclass()
class User:
    id: str
    visitor_id: Optional[str]
    email: Optional[str]
    name: Optional[str]
    created_at: datetime.datetime
    last_seen_at: Optional[datetime.datetime]
    total_sessions: int
    total_bookings: int


@dataclasses.dataclass()
class UserProfile:
    user_id: str
    company: Optional[str]
    domain: Optional[str]
    last_intent_type: Optional[str]
    booked_before: bool
    last_visit_at: datetime.datetime
    created_at: datetime.datetime
